# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ventana.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(595, 562)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ico.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.ConvertirGrupo = QtWidgets.QGroupBox(Dialog)
        self.ConvertirGrupo.setGeometry(QtCore.QRect(50, 60, 531, 151))
        self.ConvertirGrupo.setTitle("")
        self.ConvertirGrupo.setObjectName("ConvertirGrupo")
        self.covertirCheck = QtWidgets.QCheckBox(self.ConvertirGrupo)
        self.covertirCheck.setGeometry(QtCore.QRect(20, 20, 231, 17))
        self.covertirCheck.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.covertirCheck.setChecked(True)
        self.covertirCheck.setTristate(False)
        self.covertirCheck.setObjectName("covertirCheck")
        self.ConvertirBar = QtWidgets.QProgressBar(self.ConvertirGrupo)
        self.ConvertirBar.setGeometry(QtCore.QRect(170, 20, 331, 23))
        self.ConvertirBar.setProperty("value", 0)
        self.ConvertirBar.setTextVisible(True)
        self.ConvertirBar.setInvertedAppearance(False)
        self.ConvertirBar.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.ConvertirBar.setObjectName("ConvertirBar")
        self.ratebar = QtWidgets.QSlider(self.ConvertirGrupo)
        self.ratebar.setGeometry(QtCore.QRect(70, 120, 160, 19))
        self.ratebar.setAccessibleName("")
        self.ratebar.setAccessibleDescription("")
        self.ratebar.setMinimum(1)
        self.ratebar.setProperty("value", 90)
        self.ratebar.setOrientation(QtCore.Qt.Horizontal)
        self.ratebar.setObjectName("ratebar")
        self.criterio = QtWidgets.QCheckBox(self.ConvertirGrupo)
        self.criterio.setGeometry(QtCore.QRect(390, 120, 81, 17))
        self.criterio.setAccessibleName("")
        self.criterio.setAccessibleDescription("")
        self.criterio.setObjectName("criterio")
        self.label_2 = QtWidgets.QLabel(self.ConvertirGrupo)
        self.label_2.setGeometry(QtCore.QRect(30, 70, 121, 21))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.OtrasGrupo = QtWidgets.QGroupBox(Dialog)
        self.OtrasGrupo.setGeometry(QtCore.QRect(50, 210, 531, 301))
        self.OtrasGrupo.setObjectName("OtrasGrupo")
        self.duplicadosCheck = QtWidgets.QCheckBox(self.OtrasGrupo)
        self.duplicadosCheck.setEnabled(True)
        self.duplicadosCheck.setGeometry(QtCore.QRect(30, 30, 161, 17))
        self.duplicadosCheck.setChecked(True)
        self.duplicadosCheck.setObjectName("duplicadosCheck")
        self.cbzCheck = QtWidgets.QCheckBox(self.OtrasGrupo)
        self.cbzCheck.setGeometry(QtCore.QRect(30, 130, 151, 17))
        self.cbzCheck.setChecked(True)
        self.cbzCheck.setObjectName("cbzCheck")
        self.zipCheck = QtWidgets.QCheckBox(self.OtrasGrupo)
        self.zipCheck.setGeometry(QtCore.QRect(30, 80, 201, 17))
        self.zipCheck.setChecked(True)
        self.zipCheck.setObjectName("zipCheck")
        self.ordenarCheck = QtWidgets.QCheckBox(self.OtrasGrupo)
        self.ordenarCheck.setGeometry(QtCore.QRect(30, 180, 231, 16))
        self.ordenarCheck.setChecked(False)
        self.ordenarCheck.setObjectName("ordenarCheck")
        self.eliminarCheck = QtWidgets.QCheckBox(self.OtrasGrupo)
        self.eliminarCheck.setGeometry(QtCore.QRect(30, 270, 171, 17))
        self.eliminarCheck.setChecked(True)
        self.eliminarCheck.setObjectName("eliminarCheck")
        self.duplicadosBar = QtWidgets.QProgressBar(self.OtrasGrupo)
        self.duplicadosBar.setGeometry(QtCore.QRect(310, 20, 201, 23))
        self.duplicadosBar.setProperty("value", 0)
        self.duplicadosBar.setObjectName("duplicadosBar")
        self.zipBar = QtWidgets.QProgressBar(self.OtrasGrupo)
        self.zipBar.setGeometry(QtCore.QRect(310, 70, 201, 23))
        self.zipBar.setProperty("value", 0)
        self.zipBar.setObjectName("zipBar")
        self.cbzBar = QtWidgets.QProgressBar(self.OtrasGrupo)
        self.cbzBar.setGeometry(QtCore.QRect(310, 120, 201, 23))
        self.cbzBar.setProperty("value", 0)
        self.cbzBar.setObjectName("cbzBar")
        self.ordenarBar = QtWidgets.QProgressBar(self.OtrasGrupo)
        self.ordenarBar.setGeometry(QtCore.QRect(310, 170, 201, 23))
        self.ordenarBar.setProperty("value", 0)
        self.ordenarBar.setObjectName("ordenarBar")
        self.residualesBar = QtWidgets.QProgressBar(self.OtrasGrupo)
        self.residualesBar.setGeometry(QtCore.QRect(320, 270, 201, 23))
        self.residualesBar.setProperty("value", 0)
        self.residualesBar.setObjectName("residualesBar")
        self.inteligenteRadio = QtWidgets.QRadioButton(self.OtrasGrupo)
        self.inteligenteRadio.setGeometry(QtCore.QRect(100, 230, 82, 17))
        self.inteligenteRadio.setChecked(True)
        self.inteligenteRadio.setObjectName("inteligenteRadio")
        self.brutoRadio = QtWidgets.QRadioButton(self.OtrasGrupo)
        self.brutoRadio.setGeometry(QtCore.QRect(260, 230, 82, 17))
        self.brutoRadio.setObjectName("brutoRadio")
        self.manga = QtWidgets.QLineEdit(Dialog)
        self.manga.setGeometry(QtCore.QRect(170, 30, 381, 21))
        self.manga.setInputMethodHints(QtCore.Qt.ImhNone)
        self.manga.setDragEnabled(True)
        self.manga.setClearButtonEnabled(True)
        self.manga.setObjectName("manga")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(40, 30, 121, 21))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.Iniciar = QtWidgets.QPushButton(Dialog)
        self.Iniciar.setGeometry(QtCore.QRect(140, 520, 91, 31))
        self.Iniciar.setObjectName("Iniciar")
        self.Reiniciar = QtWidgets.QPushButton(Dialog)
        self.Reiniciar.setGeometry(QtCore.QRect(360, 520, 91, 31))
        self.Reiniciar.setObjectName("Reiniciar")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Compresor de Mangas S"))
        self.covertirCheck.setText(_translate("Dialog", "Comprimir imagenes"))
        self.criterio.setText(_translate("Dialog", "Por defecto"))
        self.label_2.setText(_translate("Dialog", "Criterio de compresión:"))
        self.OtrasGrupo.setTitle(_translate("Dialog", "GroupBox"))
        self.duplicadosCheck.setText(_translate("Dialog", "Eliminar archivos duplicados"))
        self.cbzCheck.setText(_translate("Dialog", "Transformar de zip a cbz"))
        self.zipCheck.setText(_translate("Dialog", "Comprimir carpetas en el interior a zip"))
        self.ordenarCheck.setText(_translate("Dialog", "Ordenar los cbz en formato numérico"))
        self.eliminarCheck.setText(_translate("Dialog", "Eliminar carpetas residuales"))
        self.inteligenteRadio.setText(_translate("Dialog", "inteligente"))
        self.brutoRadio.setText(_translate("Dialog", "bruto"))
        self.label.setText(_translate("Dialog", "Carpeta Objetivo"))
        self.Iniciar.setText(_translate("Dialog", "Iniciar"))
        self.Reiniciar.setText(_translate("Dialog", "Reiniciar"))

